name: release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:

  create-build-push:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/anothrNick/github-tag-action
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # https://github.com/tinyrewards/action-gh-release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.tag }}
          name: Release ${{ steps.bump_version.outputs.tag }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
